<?php use_layout(':admin/layout') ?>
<?php start_block('content') ?>

<h1 class="title"><?= $title ?></h1>

<div style="float: right; padding-left: 1rem;">
    <?= $this->fetch(':admin/form-action-back') ?>
</div>
<?php if (!$record->hasLocalizedText()): ?>
    <div style="clear: both; height: 1rem"></div>
<?php endif ?>

<?= $this->fetch(':admin/form-locale-tabs') ?>        

<form action="<?= route_url($action, ['id' => $id, 'back' => $back]) ?>" method="POST">    
    <?= $form->fetch() ?>
</form>

<?php end_block() ?>