<!DOCTYPE html>
<html>
<head>
<base href="<?= route_url() ?>">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php use_css('/modules/minicore-admin/static/admin.css') ?>
<?= fetch_styles() ?>
</head>
<body>

<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="container">
        
        <!-- logo -->
        <div class="navbar-brand">
            <a class="navbar-item" href="<?= route_url('') ?>"></a>
            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar_menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbar_menu" class="navbar-menu">
            <?= $this->fetch(':admin/navbar') ?>
        </div>
    </div>
</nav>
    
<div class="container admin-container">
    <div class="columns">
        <div class="column is-2 admin-menu">
            <aside class="menu">
                <!-- 
                <p class="menu-label">General</p>
                <ul class="menu-list">
                    <li><a href="">Dashboard</a></li>
                </ul>
                -->
                <?= $this->fetch(':admin/sidebar') ?>
            </aside>    
        </div>
        <div class="column is-10">
            <?= fetch_block('content') ?>
        </div>
    </div>
</div>    
<?= fetch_scripts() ?>
</body>
</html>