<div class="table-container">
    <table class="table is-striped is-fullwidth admin-list-table">
        <thead>
            <tr>
                <?php if ($listView->hasCheckboxes()): ?>
                    <th><input type="checkbox" id="list_checkbox"></th>
                <?php endif ?>
                <?php if ($listView->getItemActions()): ?>
                    <th></th>
                <?php endif ?>
                <?= $listView->fetchHeaders() ?>
            </tr>
        </thead>
        <tbody>            
            <?php foreach ($records as $record):  ?>
                <tr>
                    <?php if ($listView->hasCheckboxes()): ?>
                        <td><input class="list-id-checkbox" type="checkbox" value="<?= $record->get('id') ?>"></td>
                    <?php endif ?>
                    <?php if ($listView->getItemActions()): ?>
                        <td>
                            <?= $listView->fetchItemActions($record) ?>
                        </td>
                    <?php endif ?>
                    <?= $listView->fetchRecord($record) ?>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>