<div class="level-item">
    <div class="field has-addons">
        <div class="control is-expanded">
            <div class="select">
                <select id="page_limit_select" data-url="<?= route_url($adminService->getListRoute()) ?>">
                    <?php foreach ([5, 10, 25, 50] as $number): ?>
                        <option value="<?= $number ?>"<?= $filter['page_limit'] == $number ? ' selected' : '' ?>><?= $number ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="control">
            <a class="button is-static"><?= text('admin', 'per_page') ?></a>
        </div>
    </div>            
</div>