<?php use_layout(':admin/layout') ?>
<?php use_script('/modules/minicore-admin/static/list.js') ?>
<?php start_block('content') ?>

<h1 class="title"><?= $adminService->getTitle(AdminService::LIST) ?></h1>

<?= $this->fetch(':admin/list-message') ?>

<div class="level">
    <div class="level-left">
        <?= $this->fetch(':admin/list-filter') ?>        
    </div>
    <div class="level-right">        
        <?= $this->fetch(':admin/list-page-limit') ?>        
    </div>
</div>
    
<?= $this->fetch(':admin/list-view') ?>

<?php end_block() ?>