<div class="table-container">
    <table class="table is-striped is-fullwidth">
        <thead>
            <th><input type="checkbox" id="list_checkbox"></th>
            <?= $listView->fetchHeaders() ?>
            <th></th>
        </thead>
        <tbody>            
            <?php foreach ($records as $record):  ?>
                <tr>
                    <td><input class="list-id-checkbox" type="checkbox" name="id[]" value="<?= $record->get('id') ?>"></td>
                    <?= $listView->fetchRecord($record) ?>
                    <td style="text-align: right">
                        <?= $listView->fetchItemActions($record) ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>