<div class="level-item">
    <button type="button" id="delete_button" class="button list-action" data-action="<?= route_url($adminService->getDeleteRoute()) ?>" data-method="DELETE" data-confirm="<?= text('admin', 'confirm_delete_selected') ?>">
        <span class="icon" style="padding: 0 1.5rem 0 0.8rem"><i class="fas fa-trash"></i></span>
        <?= text('admin', 'delete_selected') ?>
    </button>
</div>