<?php if ($listView->getActions()): ?>
    <div class="level">
        <div class="level-left">
            <?= $listView->fetchActions() ?>
        </div>
        <div class="level-right">        
            <?= $this->fetch(':admin/list-page-limit') ?>        
        </div>            
    </div>
<?php endif ?>

<?php if ($records): ?>
    <?= $pager->fetch() ?>
    <?= $listView->fetchTable($records) ?>
    <?= $pager->fetch() ?>    
<?php else: ?>
    <?= $this->fetch(':admin/list-no-results') ?>  
<?php endif ?>
