<?php use_layout(':admin/layout') ?>
<?php use_module_script('minicore-admin', 'static/list.js') ?>
<?php use_module_script('minicore-admin', 'static/notification.js') ?>
<?php start_block('content') ?>

<h1 class="title"><?= $adminService->getTitle(AdminService::LIST) ?></h1>

<?= $this->fetch(':admin/list-message') ?>

<div class="level">
    <div class="level-left">
        <?= $this->fetch(':admin/list-filter') ?>        
    </div>
</div>
    
<?= $this->fetch(':admin/list-view') ?>

<?php end_block() ?>