<!-- filter -->
<div class="level-item">
    <form action="<?= route_url($adminService->getListRoute()) ?>" method="GET" id="filter_form">
        <?= $filterForm->fetch(':admin/list-filter-form', ['route' => $adminService->getListRoute(true), 'router' => $router]) ?>
    </form>
</div>
<?php if ($adminService->showRemoveFilter($filter)): ?>
    <div class="level-item">
        <a class="button is-light" href="<?= $adminService->getRemoveFilterUrl() ?>"><span class="icon" style="padding: 0 1.5rem 0 0.8rem"><i class="fas fa-times"></i></span>Remove filter</a>
    </div>
<?php endif ?>