<!-- menu left
<div class="navbar-start">
    <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">Dropdown menu</a>
        <div class="navbar-dropdown">
            <a class="navbar-item" href="">Dropdown menuitem</a>
        </div>
    </div>
</div>-->

<!-- menu right
<div class="navbar-end">
    <div class="navbar-item">
        <div class="buttons">
            <a class="button is-dark">
                <span class="icon"><i class="fas fa-bell"></i></span>
                <span class="icon-number">99</span>
            </a>
        </div>
    </div>
</div>
-->