<?php if ($pager->getMax() > 0): ?>
<nav class="pagination is-left is-small" role="navigation" aria-label="pagination" style="margin-bottom: 0.5rem;">
<a class="pagination-previous"<?= $pager->hasPrev() ? '' : ' disabled' ?> href="<?= $pager->getUrl($pager->getPage() - 1) ?>"><?= text('admin', 'previous') ?></a>
<a class="pagination-next"<?= $pager->hasNext() ? '' : ' disabled' ?> href="<?= $pager->getUrl($pager->getPage() + 1) ?>"><?= text('admin', 'next') ?></a>
    <ul class="pagination-list">
        <?php if ($pager->getStart() != 0): ?>
            <li>
                <a href="<?= $pager->getUrl(0) ?>" class="pagination-link<?= $pager->getPage() == 0 ? ' is-current' : '' ?>">1</a>
            </li>
        <?php endif ?>
        <?php if ($pager->hasLeftHidden()): ?>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        <?php endif ?>
        <?php for ($i = $pager->getStart(); $i <= $pager->getEnd(); $i++): ?>
            <li>
                <a href="<?= $pager->getUrl($i) ?>" class="pagination-link<?= $pager->getPage() == $i ? ' is-current' : '' ?>">
                    <?= $i + 1 ?>
                </a>
            </li>
        <?php endfor ?>
        <?php if ($pager->hasRightHidden()): ?>
            <li><span class="pagination-ellipsis">&hellip;</span></li>
        <?php endif ?>
        <?php if ($pager->getEnd() != $pager->getMax()): ?>
            <li>
                <a href="<?= $pager->getUrl($pager->getMax()) ?>" class="pagination-link<?= $pager->getPage() == $pager->getMax() ? ' is-current' : '' ?>">
                    <?= $pager->getMax() + 1 ?>
                </a>
            </li>
        <?php endif ?>
    </ul>
</nav>
<?php endif ?>