<?php use_layout(':app/login-layout') ?>
<?php start_block('content') ?>
<h1 class="title"><?= text('user', 'login') ?></h1>
<form action="<?= route_url('login') ?>" method="post">
    <?= $form->fetch() ?>
</form>
<div class="field is-horizontal">
    <div class="field-label"><label class="label"></label></div>
    <div class="field-body">
        <div class="field">
            <div class="control">
                <a href="<?= route_url('forgot') ?>"><?= text('user', 'forgotten_password') ?></a>
            </div>
        </div>
    </div>
</div>

<?php end_block() ?>